### ISSUE TITLE
Support of ZuluSCSI Mini RP2040

### ISSUE THREAD

**Issue by leonkiriliuk** [saybur/dac-attack#1]
Is adding support to the ZuluSCSI Mini RP2040 external ever possible? I see that the SDA and SCL pins are available but I suspect a board revision might be required.

How do external SCSI drives even get their audio back into the computer when playing music CDs? Do they feed the analog audio into the mic in port of sound cards?

Picture of PCB can be seen here: https://store.rabbitholecomputing.com/ZuluSCSI-Mini-RP2040-p/zuluscsi-mini-rp2040-db25.htm

**Comment by saybur** [comment]
I did a quick glance at the ZuluSCSI firmware source and I didn't see any GPIO changes that would affect the expansion pins on that model. That said I don't own one of those so I can't test to be 100% sure.

If you want to manually check, you could use a multimeter and verify continuity between the RP2040 GPIO14 (pin 17) to SDA, and GPIO15 (pin 18) to SCL. It might also be worth opening a discussion topic over at the main project or emailing RHC, they are obviously the authority on how their boards are wired and could get you an official answer.

The physical limitations are probably a bigger deal IMHO. This might be a case where hooking up a Toslink module (Everlight PLT237/T10WH) is the way to go rather than fabbing a DAC yourself - you'll probably end up with an external DAC anyway, so might as well keep the custom hardware as simple as possible.
